import java.util.Scanner;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.util.ArrayList;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class Main {
    public static void main(String[] args) {
        Scanner myScanner = new Scanner(System.in);
        boolean programRunning = true;

        // ==========================================
        // SYSTEM DIRECTORIES (In-Memory Data)
        // ==========================================
        ArrayList<Customer> customerDirectory = new ArrayList<>();
        ArrayList<Vehicle> vehicleDirectory = new ArrayList<>();
        ArrayList<QuotationPolicy> quoteDirectory = new ArrayList<>();

        while (programRunning) {
            // Main Menu
            System.out.println("\n=================================");
            System.out.println("   MUNSTER MOTOR INSURANCE");
            System.out.println("=================================");
            System.out.println("1. Customer Menu");
            System.out.println("2. Vehicle Menu");
            System.out.println("3. Quotation Calculator");
            System.out.println("4. Reports Menu");
            System.out.println("0. Exit System");
            System.out.println("---------------------------------");
            System.out.print("Enter your choice (0-4): ");

            String userInput = myScanner.nextLine();

            // ==========================================
            // 1. CUSTOMER MENU
            // ==========================================
            if(userInput.equals("1")){
                System.out.println("\n--- CUSTOMER MENU ---");
                System.out.println("1. Register New Customer");
                System.out.println("2. View Existing Customers");
                System.out.print("Select an option: ");
                String Input = myScanner.nextLine();

                if (Input.equals("1")){
                    System.out.println("\n>>> NEW CUSTOMER REGISTRATION <<<");
                    System.out.print("First Name (e.g., John): ");
                    String CustomerFirstName= myScanner.nextLine();

                    System.out.print("Surname (e.g., Ryan): ");
                    String CustomerSurname= myScanner.nextLine();

                    System.out.print("Address (e.g., 23 Mulgrave St): ");
                    String CustomerAddress= myScanner.nextLine();

                    System.out.print("City (e.g., Limerick): ");
                    String CustomerCity= myScanner.nextLine();

                    System.out.print("Date of Birth (DD/MM/YYYY): ");
                    String CustomerDOB= myScanner.nextLine();

                    System.out.print("Gender (M for Male, F for Female): ");
                    String CustomerGender= myScanner.nextLine().toUpperCase();

                    System.out.print("Phone Number (e.g., 0871234567): ");
                    String CustomerPhoneNumber= myScanner.nextLine();

                    System.out.print("Email (e.g., name@email.com): ");
                    String CustomerEmail= myScanner.nextLine();

                    int autoGeneratedID = (int) (Math.random() * 9000) + 1000;

                    // OOP: Creating the Customer object and adding it to the Directory list
                    Customer newCustomer = new Customer(autoGeneratedID, CustomerFirstName, CustomerSurname, CustomerAddress, CustomerCity, CustomerDOB, CustomerGender, CustomerPhoneNumber, CustomerEmail);
                    customerDirectory.add(newCustomer);

                    System.out.println("\n[!] SUCCESS: System generated Customer ID: " + autoGeneratedID);

                    // Saving data to a TXT file
                    try {
                        File myObj = new File( CustomerFirstName+"_"+CustomerSurname+".txt");
                        if (!myObj.createNewFile()) {
                            System.out.println("[i] Notice: File already exists. Overwriting data.");
                        }
                        FileWriter myWriter= new FileWriter(CustomerFirstName+"_"+CustomerSurname+".txt");
                        myWriter.write(newCustomer.DisplayDetails());
                        myWriter.close();
                    } catch (IOException e) {
                        System.out.println("[X] An error occurred saving the file.");
                    }
                    System.out.println(">>> " + CustomerFirstName + " has been successfully added to the system! <<<");
                }
                else if (Input.equals("2")) {
                    System.out.println("\n>>> REGISTERED CUSTOMERS IN SESSION <<<");
                    System.out.println("---------------------------------------------");
                    if (customerDirectory.isEmpty()) {
                        System.out.println("No customers registered in this session yet.");
                    } else {
                        for (Customer c : customerDirectory) {
                            System.out.println(c.DisplayDetails());
                            System.out.println("---------------------------------------------");
                        }
                    }
                } else {
                    System.out.println("\n[X] Invalid option selected. Returning to main menu.");
                }
            }

            // ==========================================
            // 2. VEHICLE MENU
            // ==========================================
            else if(userInput.equals("2")){
                System.out.println("\n--- VEHICLE MENU ---");
                System.out.println("1. Register New Vehicle");
                System.out.println("2. View Existing Vehicles");
                System.out.print("Select an option: ");
                String Input = myScanner.nextLine();

                if (Input.equals("1")){
                    System.out.println("\n>>> NEW VEHICLE REGISTRATION <<<");
                    System.out.print("Vehicle Make (e.g., Volkswagen): ");
                    String VehicleMake= myScanner.nextLine();

                    System.out.print("Vehicle Model (e.g., Golf): ");
                    String VehicleModel= myScanner.nextLine();

                    System.out.print("Vehicle Year (YYYY): ");
                    String VehicleYearStr= myScanner.nextLine();
                    int VehicleYear = 0;
                    try {
                        VehicleYear = Integer.parseInt(VehicleYearStr);
                    } catch (NumberFormatException e) {
                        System.out.println("[X] Invalid year format. Defaulting to 2000.");
                        VehicleYear = 2000;
                    }

                    System.out.print("Vehicle Color (e.g., Blue): ");
                    String VehicleColor= myScanner.nextLine();

                    int autoGeneratedVehicleID = (int) (Math.random() * 9000) + 1000;

                    // OOP: Creating the Vehicle object and adding it to the Directory list
                    Vehicle newVehicle = new Vehicle(autoGeneratedVehicleID, VehicleMake, VehicleModel, VehicleYear, VehicleColor);
                    vehicleDirectory.add(newVehicle);

                    System.out.println("\n[!] SUCCESS: System generated Vehicle ID: " + autoGeneratedVehicleID);

                    // Saving data to a TXT file
                    try {
                        FileWriter myWriter= new FileWriter(VehicleMake+"_"+VehicleYear+".txt");
                        myWriter.write(newVehicle.DisplayDetails());
                        myWriter.close();
                    } catch (IOException e) {
                        System.out.println("[X] An error occurred saving the file.");
                    }
                    System.out.println(">>> " + VehicleMake + " " + VehicleModel + " added successfully! <<<");
                }
                else if (Input.equals("2")) {
                    System.out.println("\n>>> REGISTERED VEHICLES IN SESSION <<<");
                    System.out.println("---------------------------------------------");
                    if (vehicleDirectory.isEmpty()) {
                        System.out.println("No vehicles registered in this session yet.");
                    } else {
                        for (Vehicle v : vehicleDirectory) {
                            System.out.println(v.DisplayDetails());
                            System.out.println("---------------------------------------------");
                        }
                    }
                } else {
                    System.out.println("\n[X] Invalid option selected. Returning to main menu.");
                }
            }

            // ==========================================
            // 3. QUOTATION CALCULATOR
            // ==========================================
            else if(userInput.equals("3")){
                System.out.println("\n>>> LINK NEW QUOTATION <<<");
                System.out.println("==========================================");

                // SAFETY LOCK: Requires at least 1 Customer and 1 Vehicle registered
                if (customerDirectory.isEmpty() || vehicleDirectory.isEmpty()) {
                    System.out.println("[X] WARNING: You must register at least 1 Customer and 1 Vehicle first!");
                    System.out.println("Returning to Main Menu...");
                    continue; // Skips back to the main menu loop
                }

                try {
                    // DISPLAYING AVAILABLE CUSTOMERS
                    System.out.println("\n--- AVAILABLE CUSTOMERS ---");
                    for (Customer c : customerDirectory) {
                        System.out.println("[ ID: " + c.CustomerID + " ] - " + c.FirstName + " " + c.Surname);
                    }
                    System.out.print("-> Enter Customer ID from the list above: ");
                    int cID = Integer.parseInt(myScanner.nextLine());

                    // FIND CUSTOMER TO EXTRACT DATA AUTOMATICALLY
                    Customer selectedCustomer = null;
                    for (Customer c : customerDirectory) {
                        if (c.CustomerID == cID) {
                            selectedCustomer = c;
                            break;
                        }
                    }
                    if (selectedCustomer == null) {
                        System.out.println("\n[X] Error: Customer ID not found. Returning to menu.");
                        continue;
                    }

                    // DISPLAYING AVAILABLE VEHICLES
                    System.out.println("\n--- AVAILABLE VEHICLES ---");
                    for (Vehicle v : vehicleDirectory) {
                        System.out.println("[ ID: " + v.VehicleID + " ] - " + v.Make + " " + v.Model + " (" + v.Year + ")");
                    }
                    System.out.print("-> Enter Vehicle ID from the list above: ");
                    int vID = Integer.parseInt(myScanner.nextLine());

                    // --- SMART EXTRACTION (Gender & Age) ---
                    String qGender = selectedCustomer.Gender;
                    int qAge = 0;
                    try {
                        // Takes the last 4 characters of DOB (e.g., 1990 from "01/01/1990")
                        int birthYear = Integer.parseInt(selectedCustomer.DOB.substring(selectedCustomer.DOB.length() - 4));
                        qAge = 2026 - birthYear; // Calculates age based on current system year
                    } catch (Exception e) {
                        System.out.print("[!] Could not auto-calculate age from DOB. Enter Age manually: ");
                        qAge = Integer.parseInt(myScanner.nextLine());
                    }

                    System.out.println("\n[i] Smart Extraction: Auto-loaded from Customer Profile!");
                    System.out.println("    - Gender: " + qGender);
                    System.out.println("    - Age: " + qAge + " years old");

                    // County Mapping
                    System.out.println("\nSelect County: 1.Cork  2.Clare  3.Kerry  4.Limerick  5.Tipperary  6.Waterford");
                    System.out.print("Choice (1-6): ");
                    String countyChoice = myScanner.nextLine();
                    String qCounty = "";
                    switch(countyChoice) {
                        case "1": qCounty = "Cork"; break;
                        case "2": qCounty = "Clare"; break;
                        case "3": qCounty = "Kerry"; break;
                        case "4": qCounty = "Limerick"; break;
                        case "5": qCounty = "Tipperary"; break;
                        case "6": qCounty = "Waterford"; break;
                        default: qCounty = "Other"; break;
                    }

                    // Make Mapping
                    System.out.println("\nSelect Make: 1.BMW  2.Opel  3.Toyota  4.Renault");
                    System.out.print("Choice (1-4): ");
                    String makeChoice = myScanner.nextLine();
                    String qMake = "";
                    String qModel = "";

                    if (makeChoice.equals("1")) {
                        qMake = "BMW";
                        System.out.println("Select Model: 1.Convertible  2.Gran Turismo  3.BMW X6  4.BMW Z4");
                        System.out.print("Choice: ");
                        String mChoice = myScanner.nextLine();
                        if (mChoice.equals("1")) qModel = "Convertible";
                        else if (mChoice.equals("2")) qModel = "Gran Turismo";
                        else if (mChoice.equals("3")) qModel = "BMW X6";
                        else if (mChoice.equals("4")) qModel = "BMW Z4";
                    }
                    else if (makeChoice.equals("2")) {
                        qMake = "Opel";
                        System.out.println("Select Model: 1.Corsa  2.Astra  3.Vectra");
                        System.out.print("Choice: ");
                        String mChoice = myScanner.nextLine();
                        if (mChoice.equals("1")) qModel = "Corsa";
                        else if (mChoice.equals("2")) qModel = "Astra";
                        else if (mChoice.equals("3")) qModel = "Vectra";
                    }
                    else if (makeChoice.equals("3")) {
                        qMake = "Toyota";
                        System.out.println("Select Model: 1.Yaris  2.Auris  3.Corolla  4.Avensis");
                        System.out.print("Choice: ");
                        String mChoice = myScanner.nextLine();
                        if (mChoice.equals("1")) qModel = "Yaris";
                        else if (mChoice.equals("2")) qModel = "Auris";
                        else if (mChoice.equals("3")) qModel = "Corolla";
                        else if (mChoice.equals("4")) qModel = "Avensis";
                    }
                    else if (makeChoice.equals("4")) {
                        qMake = "Renault";
                        System.out.println("Select Model: 1.Fleunce  2.Megane  3.Clio");
                        System.out.print("Choice: ");
                        String mChoice = myScanner.nextLine();
                        if (mChoice.equals("1")) qModel = "Fleunce";
                        else if (mChoice.equals("2")) qModel = "Megane";
                        else if (mChoice.equals("3")) qModel = "Clio";
                    }

                    // Emissions Mapping
                    System.out.println("\nSelect Emissions: 1.High  2.Medium  3.Low");
                    System.out.print("Choice (1-3): ");
                    String emChoice = myScanner.nextLine();
                    String qEmissions = "";
                    if (emChoice.equals("1")) qEmissions = "High";
                    else if (emChoice.equals("2")) qEmissions = "Medium";
                    else if (emChoice.equals("3")) qEmissions = "Low";

                    // Insurance Category Mapping
                    System.out.println("\nSelect Category: 1.Fully Comprehensive Plus  2.Third Party Fire and Theft");
                    System.out.print("Choice (1-2): ");
                    String catChoice = myScanner.nextLine();
                    String qCategory = "";
                    if (catChoice.equals("1")) qCategory = "Fully Comprehensive Plus";
                    else if (catChoice.equals("2")) qCategory = "Third Party Fire and Theft";

                    // Creating the quotation object
                    QuotationPolicy newQuote = new QuotationPolicy(cID, vID, qGender, qAge, qCounty, qMake, qModel, qEmissions, qCategory);
                    quoteDirectory.add(newQuote);

                    System.out.println("\n==========================================");
                    System.out.println(newQuote.DisplayDetails());
                    System.out.println("==========================================");

                    // Saving the quote
                    if (!newQuote.isDeclined) {
                        try {
                            FileWriter quoteWriter = new FileWriter("Quote_" + newQuote.quoteID + ".txt");
                            quoteWriter.write(newQuote.DisplayDetails());
                            quoteWriter.close();
                            System.out.println("[!] Quote saved to disk successfully.");
                        } catch (IOException e) {
                            System.out.println("[X] Failed to save quote file.");
                        }
                    }
                } catch (NumberFormatException e) {
                    System.out.println("\n[X] Error: Invalid number format. Please enter numbers only for IDs and Age.");
                }
            }

            // ==========================================
            // 4. REPORTS MENU
            // ==========================================
            else if(userInput.equals("4")){
                System.out.println("\n--- REPORTS MENU ---");
                System.out.println("1. Historical Incident Reports");
                System.out.println("2. Generate Certificates of Motor Insurance (NEW ✨)");
                System.out.print("Select an option: ");
                String repInput = myScanner.nextLine();

                if (repInput.equals("1")) {
                    System.out.println("\n>>> INCIDENT REPORTS <<<");
                    System.out.println("======================================");
                    System.out.println("REPORT #001");
                    Reports report1 = new Reports("Mary O'Shea","12/01/2026","15:15","Ennis Rd, Limerick","My car, a 2008 red Nissan Micra, collided with a 2010 blue Renault Zoe near the Jetland Shopping Centre on Ennis Road, Limerick. No injuries were sustained.","Minor damage to right wing-mirror and right headlight.","13/02/2026.");
                    System.out.println(report1.DisplayDetails());
                    System.out.println("======================================");
                }
                else if (repInput.equals("2")) {
                    System.out.println("\n>>> CERTIFICATES OF MOTOR INSURANCE <<<");
                    if (quoteDirectory.isEmpty()) {
                        System.out.println("[i] No quotations have been generated in this session yet.");
                    } else {
                        // Setting up dynamic dates (Today and 1 year in the future)
                        LocalDate today = LocalDate.now();
                        LocalDate nextYear = today.plusYears(1);
                        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                        String effectiveDate = today.format(formatter);
                        String expiryDate = nextYear.format(formatter);

                        // Iterating through the generated quotes to build the official certificates
                        for (QuotationPolicy q : quoteDirectory) {

                            // Skips declined quotes (no certificate should be issued)
                            if (q.isDeclined) continue;

                            // 1. Find matching Customer
                            Customer matchedCustomer = null;
                            for (Customer c : customerDirectory) {
                                if (c.CustomerID == q.customerID) { matchedCustomer = c; break; }
                            }

                            // 2. Find matching Vehicle
                            Vehicle matchedVehicle = null;
                            for (Vehicle v : vehicleDirectory) {
                                if (v.VehicleID == q.vehicleID) { matchedVehicle = v; break; }
                            }

                            // 3. Visual Assembly of the Certificate (Matching the physical document)
                            if (matchedCustomer != null && matchedVehicle != null) {
                                String certificate =
                                        "\nCertificate of Motor Insurance\n\n" +
                                                "Munster Motor Insurance\n\n" +
                                                "1. Certificate Number [" + q.quoteID + "]\n\n" +
                                                "2. Description of Vehicle [" + matchedVehicle.Make + "] - [" + matchedVehicle.Model + "] - [" + matchedVehicle.Year + "]\n\n" +
                                                "3. Name of Policyholder [" + matchedCustomer.FirstName + " " + matchedCustomer.Surname + "]\n\n" +
                                                "4. Effective date of the commencement of insurance [" + effectiveDate + " at 00:00:01]\n\n" +
                                                "5. Date of expiry of insurance [Midnight " + expiryDate + "]\n\n" +
                                                "6. Person or classes of person entitled to drive as defined below\n" +
                                                "D - Any person who is driving with the policyholder's consent.\n\n" +
                                                "Provided that the person driving holds a licence to drive the vehicle or has held and is not disqualified\n" +
                                                "from holding or obtaining such a licence.\n\n" +
                                                "7. Limitations as to use as defined below\n" +
                                                "Use in connection with the policyholder's business excluding use for hire and/or reward.\n" +
                                                "Use for social, domestic and pleasure purposes only.\n\n" +
                                                "8. The policy does not cover\n\n" +
                                                "    • Carriage of passengers for hire and/or reward\n" +
                                                "    • Racing, pace-setting, speed trials, motor rallies, competitions or trials\n" +
                                                "    • Use in connection with the Motor Trade\n" +
                                                "    • Towing for reward a mechanically propelled vehicle\n" +
                                                "    • Semi-trailer being part of an articulated vehicle\n\n" +
                                                "--------------------------------------------------------------------------------------------------------\n" +
                                                "I hereby certify that the document to which this certificate relates satisfies the requirements of the relevant law applicable in\n" +
                                                "Great Britain, Northern Ireland, the Isle of Man, the Island of Guernsey, the Island of Jersey and the Island of Alderney.\n" +
                                                "--------------------------------------------------------------------------------------------------------\n\n" +
                                                "Munster Motor Insurance\n" +
                                                "Thomond Park House\n" +
                                                "Limerick\n\n" +
                                                "Signed:\n" +
                                                "B. D. Carpenters\n" +
                                                "*Underwriter\n" +
                                                "========================================================================================================\n";

                                // Print to console
                                System.out.println(certificate);

                                // Save automatically to a clean .txt file for future printing/conversion
                                try {
                                    FileWriter certWriter = new FileWriter("Certificate_" + q.quoteID + ".txt");
                                    certWriter.write(certificate);
                                    certWriter.close();
                                    System.out.println("[!] Official Certificate saved as 'Certificate_" + q.quoteID + ".txt'");
                                } catch (IOException e) {
                                    System.out.println("[X] Failed to save certificate file.");
                                }
                            }
                        }
                    }
                } else {
                    System.out.println("\n[X] Invalid option. Returning to menu.");
                }
            }

            // ==========================================
            // 0. EXIT
            // ==========================================
            else if(userInput.equals("0")){
                System.out.println("\nSaving data and shutting down system...");
                System.out.println("Goodbye!");
                programRunning = false;
            }

            // ERROR HANDLING
            else{
                System.out.println("\n[X] Invalid input. Please enter a number from 0 to 4.");
            }

            // PAUSE BEFORE RETURNING TO MENU
            if (programRunning) {
                System.out.print("\nPress ENTER to return to Main Menu...");
                myScanner.nextLine();
            }
        }

        myScanner.close();
    }
}