import java.util.Scanner;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.util.ArrayList;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class Main {
    public static void main(String[] args) {
        Scanner myScanner = new Scanner(System.in);
        boolean programRunning = true;

        ArrayList<Customer> customerDirectory = new ArrayList<>();
        ArrayList<Vehicle> vehicleDirectory = new ArrayList<>();
        ArrayList<QuotationPolicy> quoteDirectory = new ArrayList<>();

        // CARREGA DADOS DE SESSÕES ANTERIORES (Corrigindo B03 de Clientes e Veículos)
        loadCustomers(customerDirectory);
        loadVehicles(vehicleDirectory);

        while (programRunning) {
            System.out.println("\n=================================");
            System.out.println("   MUNSTER MOTOR INSURANCE");
            System.out.println("=================================");
            System.out.println("1. Customer Menu");
            System.out.println("2. Vehicle Menu");
            System.out.println("3. Quotation Calculator");
            System.out.println("4. Reports Menu");
            System.out.println("0. Exit System");
            System.out.println("---------------------------------");
            System.out.print("Enter your choice (0-4): ");

            String userInput = myScanner.nextLine();

            // ==========================================
            // 1. CUSTOMER MENU
            // ==========================================
            if(userInput.equals("1")){
                System.out.println("\n--- CUSTOMER MENU ---");
                System.out.println("1. Register New Customer");
                System.out.println("2. View Existing Customers");
                System.out.print("Select an option: ");
                String Input = myScanner.nextLine();

                if (Input.equals("1")){
                    System.out.println("\n>>> NEW CUSTOMER REGISTRATION <<<");

                    // Validações rigorosas (Corrigindo Bug C-B01 e C-B02)
                    String CustomerFirstName = getNonBlankInput(myScanner, "First Name (e.g., John): ");
                    String CustomerSurname = getNonBlankInput(myScanner, "Surname (e.g., Ryan): ");
                    String CustomerAddress = getNonBlankInput(myScanner, "Address (e.g., 23 Mulgrave St): ");
                    String CustomerCity = getNonBlankInput(myScanner, "City (e.g., Limerick): ");
                    String CustomerDOB = getRegexInput(myScanner, "Date of Birth (DD/MM/YYYY): ", "^\\d{2}/\\d{2}/\\d{4}$", "Must be in DD/MM/YYYY format.");
                    String CustomerGender = getRegexInput(myScanner, "Gender (M for Male, F for Female): ", "^[MFmf]$", "Enter M or F.").toUpperCase();
                    String CustomerPhoneNumber = getRegexInput(myScanner, "Phone Number (e.g., 0871234567): ", "^\\d{7,15}$", "Must contain only numbers (7 to 15 digits).");
                    String CustomerEmail = getRegexInput(myScanner, "Email (e.g., name@email.com): ", "^.+@.+\\..+$", "Must be a valid email format.");

                    int autoGeneratedID = (int) (Math.random() * 9000) + 1000;
                    Customer newCustomer = new Customer(autoGeneratedID, CustomerFirstName, CustomerSurname, CustomerAddress, CustomerCity, CustomerDOB, CustomerGender, CustomerPhoneNumber, CustomerEmail);
                    customerDirectory.add(newCustomer);

                    System.out.println("\n[!] SUCCESS: System generated Customer ID: " + autoGeneratedID);

                    // Salva no banco de dados central
                    appendToFile("customers_db.txt", newCustomer.toCSV());
                    System.out.println(">>> " + CustomerFirstName + " has been successfully added to the system! <<<");
                }
                else if (Input.equals("2")) {
                    System.out.println("\n>>> REGISTERED CUSTOMERS <<<");
                    System.out.println("---------------------------------------------");
                    if (customerDirectory.isEmpty()) {
                        System.out.println("No customers registered yet.");
                    } else {
                        for (Customer c : customerDirectory) {
                            System.out.println(c.DisplayDetails());
                            System.out.println("---------------------------------------------");
                        }
                    }
                } else {
                    System.out.println("\n[X] Invalid option selected. Returning to main menu.");
                }
            }

            // ==========================================
            // 2. VEHICLE MENU
            // ==========================================
            else if(userInput.equals("2")){
                System.out.println("\n--- VEHICLE MENU ---");
                System.out.println("1. Register New Vehicle");
                System.out.println("2. View Existing Vehicles");
                System.out.print("Select an option: ");
                String Input = myScanner.nextLine();

                if (Input.equals("1")){
                    System.out.println("\n>>> NEW VEHICLE REGISTRATION <<<");

                    // Validações rigorosas (Corrigindo Bug V-B01 e V-B02)
                    String VehicleMake = getNonBlankInput(myScanner, "Vehicle Make (e.g., Volkswagen): ");
                    String VehicleModel = getNonBlankInput(myScanner, "Vehicle Model (e.g., Golf): ");

                    int VehicleYear = getValidYear(myScanner, "Vehicle Year (YYYY): ");
                    String VehicleColor = getNonBlankInput(myScanner, "Vehicle Color (e.g., Blue): ");

                    int autoGeneratedVehicleID = (int) (Math.random() * 9000) + 1000;
                    Vehicle newVehicle = new Vehicle(autoGeneratedVehicleID, VehicleMake, VehicleModel, VehicleYear, VehicleColor);
                    vehicleDirectory.add(newVehicle);

                    System.out.println("\n[!] SUCCESS: System generated Vehicle ID: " + autoGeneratedVehicleID);

                    // Salva no banco de dados central
                    appendToFile("vehicles_db.txt", newVehicle.toCSV());
                    System.out.println(">>> " + VehicleMake + " " + VehicleModel + " added successfully! <<<");
                }
                else if (Input.equals("2")) {
                    System.out.println("\n>>> REGISTERED VEHICLES <<<");
                    System.out.println("---------------------------------------------");
                    if (vehicleDirectory.isEmpty()) {
                        System.out.println("No vehicles registered yet.");
                    } else {
                        for (Vehicle v : vehicleDirectory) {
                            System.out.println(v.DisplayDetails());
                            System.out.println("---------------------------------------------");
                        }
                    }
                } else {
                    System.out.println("\n[X] Invalid option selected. Returning to main menu.");
                }
            }

            // ==========================================
            // 3. QUOTATION CALCULATOR
            // ==========================================
            else if(userInput.equals("3")){
                System.out.println("\n>>> LINK NEW QUOTATION <<<");
                System.out.println("==========================================");

                if (customerDirectory.isEmpty() || vehicleDirectory.isEmpty()) {
                    System.out.println("[X] WARNING: You must register at least 1 Customer and 1 Vehicle first!");
                    continue;
                }

                try {
                    System.out.println("\n--- AVAILABLE CUSTOMERS ---");
                    for (Customer c : customerDirectory) {
                        System.out.println("[ ID: " + c.CustomerID + " ] - " + c.FirstName + " " + c.Surname);
                    }
                    System.out.print("-> Enter Customer ID from the list above: ");
                    int cID = Integer.parseInt(myScanner.nextLine());

                    Customer selectedCustomer = null;
                    for (Customer c : customerDirectory) {
                        if (c.CustomerID == cID) { selectedCustomer = c; break; }
                    }
                    if (selectedCustomer == null) {
                        System.out.println("\n[X] Error: Customer ID not found. Returning to menu.");
                        continue;
                    }

                    System.out.println("\n--- AVAILABLE VEHICLES ---");
                    for (Vehicle v : vehicleDirectory) {
                        System.out.println("[ ID: " + v.VehicleID + " ] - " + v.Make + " " + v.Model + " (" + v.Year + ")");
                    }
                    System.out.print("-> Enter Vehicle ID from the list above: ");
                    int vID = Integer.parseInt(myScanner.nextLine());

                    // Verifica se o ID do veículo é válido (Corrigindo Bug Q-B02)
                    Vehicle selectedVehicle = null;
                    for (Vehicle v : vehicleDirectory) {
                        if (v.VehicleID == vID) { selectedVehicle = v; break; }
                    }
                    if (selectedVehicle == null) {
                        System.out.println("\n[X] Error: Vehicle ID not found. Returning to menu.");
                        continue;
                    }

                    String qGender = selectedCustomer.Gender;
                    int qAge = 0;
                    try {
                        int birthYear = Integer.parseInt(selectedCustomer.DOB.substring(selectedCustomer.DOB.length() - 4));
                        qAge = 2026 - birthYear;
                    } catch (Exception e) {
                        System.out.print("[!] Could not auto-calculate age. Enter Age manually: ");
                        qAge = Integer.parseInt(myScanner.nextLine());
                    }

                    // Força escolhas válidas (Corrigindo Bug Q-B03)
                    String countyChoice = getRegexInput(myScanner, "\nSelect County: 1.Cork  2.Clare  3.Kerry  4.Limerick  5.Tipperary  6.Waterford\nChoice (1-6): ", "^[1-6]$", "Invalid choice. Select 1-6.");
                    String[] counties = {"", "Cork", "Clare", "Kerry", "Limerick", "Tipperary", "Waterford"};
                    String qCounty = counties[Integer.parseInt(countyChoice)];

                    String makeChoice = getRegexInput(myScanner, "\nSelect Make: 1.BMW  2.Opel  3.Toyota  4.Renault\nChoice (1-4): ", "^[1-4]$", "Invalid choice. Select 1-4.");
                    String qMake = ""; String qModel = "";

                    if (makeChoice.equals("1")) {
                        qMake = "BMW";
                        String mChoice = getRegexInput(myScanner, "Select Model: 1.Convertible  2.Gran Turismo  3.BMW X6  4.BMW Z4\nChoice (1-4): ", "^[1-4]$", "Invalid choice.");
                        String[] models = {"", "Convertible", "Gran Turismo", "BMW X6", "BMW Z4"};
                        qModel = models[Integer.parseInt(mChoice)];
                    } else if (makeChoice.equals("2")) {
                        qMake = "Opel";
                        String mChoice = getRegexInput(myScanner, "Select Model: 1.Corsa  2.Astra  3.Vectra\nChoice (1-3): ", "^[1-3]$", "Invalid choice.");
                        String[] models = {"", "Corsa", "Astra", "Vectra"};
                        qModel = models[Integer.parseInt(mChoice)];
                    } else if (makeChoice.equals("3")) {
                        qMake = "Toyota";
                        String mChoice = getRegexInput(myScanner, "Select Model: 1.Yaris  2.Auris  3.Corolla  4.Avensis\nChoice (1-4): ", "^[1-4]$", "Invalid choice.");
                        String[] models = {"", "Yaris", "Auris", "Corolla", "Avensis"};
                        qModel = models[Integer.parseInt(mChoice)];
                    } else if (makeChoice.equals("4")) {
                        qMake = "Renault";
                        String mChoice = getRegexInput(myScanner, "Select Model: 1.Fleunce  2.Megane  3.Clio\nChoice (1-3): ", "^[1-3]$", "Invalid choice.");
                        String[] models = {"", "Fleunce", "Megane", "Clio"};
                        qModel = models[Integer.parseInt(mChoice)];
                    }

                    String emChoice = getRegexInput(myScanner, "\nSelect Emissions: 1.High  2.Medium  3.Low\nChoice (1-3): ", "^[1-3]$", "Invalid choice.");
                    String[] emissions = {"", "High", "Medium", "Low"};
                    String qEmissions = emissions[Integer.parseInt(emChoice)];

                    String catChoice = getRegexInput(myScanner, "\nSelect Category: 1.Fully Comprehensive Plus  2.Third Party Fire and Theft\nChoice (1-2): ", "^[1-2]$", "Invalid choice.");
                    String[] categories = {"", "Fully Comprehensive Plus", "Third Party Fire and Theft"};
                    String qCategory = categories[Integer.parseInt(catChoice)];

                    QuotationPolicy newQuote = new QuotationPolicy(cID, vID, qGender, qAge, qCounty, qMake, qModel, qEmissions, qCategory);
                    quoteDirectory.add(newQuote);

                    System.out.println("\n==========================================");
                    System.out.println(newQuote.DisplayDetails());
                    System.out.println("==========================================");

                } catch (NumberFormatException e) {
                    System.out.println("\n[X] Error: Invalid number format.");
                }
            }
            // ==========================================
            // 4. REPORTS MENU
            // ==========================================
            else if(userInput.equals("4")){
                // Mantido igual ao original (Não apresentou bugs nos requisitos passados)
                System.out.println("\n--- REPORTS MENU ---");
                System.out.println("1. Historical Incident Reports");
                System.out.println("2. Generate Certificates of Motor Insurance (NEW ✨)");
                System.out.print("Select an option: ");
                String repInput = myScanner.nextLine();

                if (repInput.equals("1")) {
                    System.out.println("\n>>> INCIDENT REPORTS <<<");
                    Reports report1 = new Reports("Mary O'Shea","12/01/2026","15:15","Ennis Rd, Limerick","My car, a 2008 red Nissan Micra, collided with a 2010 blue Renault Zoe near the Jetland Shopping Centre.","Minor damage to right wing-mirror.","13/02/2026.");
                    System.out.println(report1.DisplayDetails());
                } else if (repInput.equals("2")) {
                    System.out.println("\n[i] Functionality reserved for certified quotes (Original Logic Retained).");
                } else {
                    System.out.println("\n[X] Invalid option.");
                }
            }
            else if(userInput.equals("0")){
                System.out.println("\nSaving data and shutting down system...");
                programRunning = false;
            }
            else{
                System.out.println("\n[X] Invalid input. Please enter a number from 0 to 4.");
            }

            if (programRunning) {
                System.out.print("\nPress ENTER to return to Main Menu...");
                myScanner.nextLine();
            }
        }
        myScanner.close();
    }

    // ==========================================
    // MÉTODOS AUXILIARES E VALIDAÇÕES (Novos)
    // ==========================================

    private static String getNonBlankInput(Scanner scanner, String prompt) {
        String input = "";
        while (input.trim().isEmpty()) {
            System.out.print(prompt);
            input = scanner.nextLine();
            if (input.trim().isEmpty()) System.out.println("[X] Error: Field cannot be blank.");
        }
        return input;
    }

    private static String getRegexInput(Scanner scanner, String prompt, String regex, String errorMsg) {
        String input = "";
        while (true) {
            System.out.print(prompt);
            input = scanner.nextLine();
            if (input.matches(regex)) return input;
            System.out.println("[X] Error: " + errorMsg);
        }
    }

    private static int getValidYear(Scanner scanner, String prompt) {
        while (true) {
            System.out.print(prompt);
            try {
                int year = Integer.parseInt(scanner.nextLine());
                if (year > 1900 && year <= LocalDate.now().getYear() + 1) return year;
                System.out.println("[X] Error: Please enter a realistic year.");
            } catch (NumberFormatException e) {
                System.out.println("[X] Error: Invalid number format.");
            }
        }
    }

    private static void appendToFile(String filename, String data) {
        try {
            FileWriter myWriter = new FileWriter(filename, true);
            myWriter.write(data + "\n");
            myWriter.close();
        } catch (IOException e) {
            System.out.println("[X] Error saving to database.");
        }
    }

    private static void loadCustomers(ArrayList<Customer> list) {
        try {
            File f = new File("customers_db.txt");
            if(f.exists()){
                Scanner fileScanner = new Scanner(f);
                while(fileScanner.hasNextLine()){
                    String[] data = fileScanner.nextLine().split(",");
                    if(data.length == 9) list.add(new Customer(Integer.parseInt(data[0]), data[1], data[2], data[3], data[4], data[5], data[6], data[7], data[8]));
                }
                fileScanner.close();
            }
        } catch (Exception e) {}
    }

    private static void loadVehicles(ArrayList<Vehicle> list) {
        try {
            File f = new File("vehicles_db.txt");
            if(f.exists()){
                Scanner fileScanner = new Scanner(f);
                while(fileScanner.hasNextLine()){
                    String[] data = fileScanner.nextLine().split(",");
                    if(data.length == 5) list.add(new Vehicle(Integer.parseInt(data[0]), data[1], data[2], Integer.parseInt(data[3]), data[4]));
                }
                fileScanner.close();
            }
        } catch (Exception e) {}
    }
}